on: [push, pull_request]
env:
  GO_VERSION: 1.23
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version: ${{ env.GO_VERSION }}
      - run: go test -v ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v6